# Generated by Django 3.2.10 on 2022-01-07 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['place__title', '-number'], 'verbose_name': 'картинка', 'verbose_name_plural': 'картинки'},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='img',
        ),
    ]
