# Generated by Django 3.2.10 on 2022-01-07 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20220107_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='coordinate_lat',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='coordinate_lng',
            new_name='lng',
        ),
    ]
