# Generated by Django 3.2.10 on 2022-01-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20220107_2115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['number'], 'verbose_name': 'картинка', 'verbose_name_plural': 'картинки'},
        ),
        migrations.AlterField(
            model_name='image',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Порядковый номер'),
        ),
    ]
